# Generated by Django 5.2.12 on 2026-09-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_consent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English'), ('fr', 'French'), ('pt', 'Portuguese'), ('it', 'Italian'), ('de', 'German')], default='', max_length=10),
        ),
    ]
