# Generated by Django 5.2.12 on 2026-09-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English'), ('fr', 'French'), ('pt', 'Portuguese'), ('it', 'Italian'), ('de', 'German'), ('nl', 'Dutch')], default='', max_length=10),
        ),
    ]
