# Generated by Django 4.1.5 on 2023-04-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principalName', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('contactName', models.CharField(max_length=50)),
                ('contactMail', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=200)),
                ('creditLogo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
    ]
