# Generated by Django 4.1.5 on 2023-05-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_administrators_organization_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ManyToManyField(blank=True, to='organizations.type'),
        ),
    ]
