# Generated by Django 4.1.5 on 2023-09-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='creditLogo',
        ),
        migrations.AddField(
            model_name='organization',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/covers/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/logos/'),
        ),
    ]
