# Generated by Django 5.2.12 on 2026-04-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_invitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
    ]
