# Generated by Django 5.2.12 on 2026-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_migrate_description_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
    ]
