# Generated by Django 4.1.5 on 2023-04-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_type', models.CharField(choices=[('STR', 'String'), ('NUM', 'Number'), ('DATE', 'Date'), ('IMG', 'Image')], max_length=4)),
                ('field_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_forms.fieldform')),
            ],
        ),
    ]
