# Generated by Django 4.1.5 on 2023-05-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='field_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='field_forms.fieldform'),
        ),
    ]
