# Generated by Django 4.1.5 on 2023-09-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_forms', '0002_alter_question_field_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
