# Generated by Django 4.1.5 on 2026-01-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_forms', '0003_question_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_help',
            field=models.TextField(blank=True, null=True),
        ),
    ]
