# Generated by Django 4.1.5 on 2026-01-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_forms', '0005_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('STR', 'String'), ('NUM', 'Number'), ('DATE', 'Date'), ('IMG', 'Image'), ('CHOICE', 'Choice')], max_length=10),
        ),
    ]
