# Generated by Django 4.1.5 on 2026-02-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_forms', '0007_alter_question_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('STR', 'String'), ('NUM', 'Number'), ('DATE', 'Date'), ('IMG', 'Image'), ('CHOICE', 'Choice'), ('MCHOICE', 'Multichoice'), ('QR', 'QR/Barcode')], max_length=10),
        ),
    ]
