# Generated by Django 4.1.5 on 2026-03-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_forms', '0009_translate_question_text_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_help',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.JSONField(),
        ),
    ]
