# Generated by Django 5.2.12 on 2026-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_forms', '0011_normalize_question_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('STR', 'String'), ('NUM', 'Number'), ('DATE', 'Date'), ('IMG', 'Image'), ('AUDIO', 'Audio'), ('CHOICE', 'Choice'), ('MCHOICE', 'Multichoice'), ('QR', 'QR/Barcode')], max_length=10),
        ),
    ]
