# Generated by Django 4.1.5 on 2023-02-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HasTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hasTag", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="asd", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="hasTag",
            field=models.ManyToManyField(blank=True, to="project.hastag"),
        ),
        migrations.AddField(
            model_name="project",
            name="topic",
            field=models.ManyToManyField(blank=True, to="project.topic"),
        ),
    ]
