# Generated by Django 4.1.5 on 2023-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_hastag_topic_project_description_project_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
