# Generated by Django 4.1.5 on 2023-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_administrators_organization_creator_and_more'),
        ('project', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(related_name='projects', to='organizations.organization'),
        ),
    ]
