# Generated by Django 4.1.5 on 2023-09-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_project_logo_projectcover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cover',
        ),
    ]
