# Generated by Django 4.1.5 on 2023-09-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
