# Generated by Django 4.1.5 on 2023-11-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project__password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='_password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
