# Generated by Django 4.1.5 on 2023-11-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_project__password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
