# Generated by Django 4.1.5 on 2026-03-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_projectinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post_observation_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
