# Generated by Django 4.1.5 on 2026-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_private_data_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='post_observation_message',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
