# Generated by Django 4.1.5 on 2026-03-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_project_email_intro_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
