# Generated by Django 4.1.5 on 2026-03-14 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_translate_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
    ]
