# Generated by Django 5.2.12 on 2026-04-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_countries_arraytojson'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
