# Generated by Django 5.2.12 on 2026-04-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_add_finalizado_to_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='finalizado',
            new_name='ended',
        ),
    ]
