# Generated by Django 5.2.12 on 2026-04-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_rename_finalizado_to_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allowed_platforms',
            field=models.CharField(choices=[('all', 'All'), ('mobile', 'Mobile only'), ('web', 'Web only')], default='all', max_length=10),
        ),
    ]
