# Generated by Django 5.2.12 on 2026-04-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_add_allowed_platforms'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectinvitation',
            unique_together=set(),
        ),
    ]
