# Generated by Django 5.2.12 on 2026-04-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_translate_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_on_observation',
            field=models.BooleanField(default=False),
        ),
    ]
