# Generated by Django 5.2.12 on 2026-04-10 16:35

from django.db import migrations, models


def set_existing_projects_published(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    Project.objects.all().update(draft=False)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_add_email_on_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_existing_projects_published, migrations.RunPython.noop),
    ]
