# Generated by Django 5.2.12 on 2026-04-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_add_draft_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_map',
            field=models.BooleanField(default=False),
        ),
    ]
