# Generated by Django 5.2.12 on 2026-04-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_add_public_map_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_observation',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
