# Generated by Django 5.2.12 on 2026-04-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_add_last_observation_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_post_message',
            field=models.BooleanField(default=False),
        ),
    ]
