# Generated by Django 5.2.12 on 2026-09-10 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_status_log(apps, schema_editor):
    """
    Siembra el historico con lo poco que se puede saber a ciencia cierta.

    - Una fila `created` por proyecto, con `created_at`: es un dato EXACTO, estimated=False.
    - Para los proyectos ya publicados (draft=False), `published_at = created_at` y una fila
      `published`, ambos ESTIMADOS (estimated=True): no hay forma de saber cuando se publicaron
      de verdad, porque `updated_at` es auto_now y solo guarda la ultima modificacion.
    - No se inventan filas `ended`: `ended` no tiene fecha en ninguna parte. El historico
      anterior a esta migracion queda incompleto en ese punto, a proposito.
    """
    Project = apps.get_model('project', 'Project')
    ProjectStatusLog = apps.get_model('project', 'ProjectStatusLog')

    rows = []
    for project in Project.objects.all().only('id', 'created_at', 'draft', 'creator_id'):
        rows.append(ProjectStatusLog(
            project_id=project.id,
            event='created',
            at=project.created_at,
            by_id=project.creator_id,
            estimated=False,
        ))
        if not project.draft:
            rows.append(ProjectStatusLog(
                project_id=project.id,
                event='published',
                at=project.created_at,
                by_id=project.creator_id,
                estimated=True,
            ))
    ProjectStatusLog.objects.bulk_create(rows, batch_size=500)

    Project.objects.filter(draft=False).update(published_at=models.F('created_at'))


def unbackfill_status_log(apps, schema_editor):
    """
    Marcha atras. Borra TODAS las filas del log, no solo las del backfill: al revertir esta
    migracion la tabla se elimina de todos modos, y dejarla a medias seria peor.
    """
    Project = apps.get_model('project', 'Project')
    ProjectStatusLog = apps.get_model('project', 'ProjectStatusLog')
    ProjectStatusLog.objects.all().delete()
    Project.objects.update(published_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_add_anonymous_contribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='ProjectStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Created'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('ended', 'Ended'), ('reopened', 'Reopened')], max_length=16)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('estimated', models.BooleanField(default=False)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_status_changes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_log', to='project.project')),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['event', 'at'], name='project_pro_event_062dfb_idx')],
            },
        ),
        migrations.RunPython(backfill_status_log, unbackfill_status_log),
    ]
