# Generated by Django 5.2.12 on 2026-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_add_published_at_and_status_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_monthly_stats',
            field=models.BooleanField(default=True),
        ),
    ]
