"""
Django settings for citsci-api project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Related with image management

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# Environment
env = environ.Env()

# Create a local.env file in the settings directory
# But ideally this env file should be outside the git repo
env_file = Path(__file__).resolve().parent / "local.env"
if env_file.exists():
    environ.Env.read_env(str(env_file))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-!rihhd3lxg-!3x8+ea*3)n9ncc7%o6%v_#ben)rui-8+@+%h@o")

# SECURITY WARNING: don't run with debug turned on in production!
# Auto-enables DEBUG when running via manage.py runserver, unless overridden by env var
import sys
DEBUG = env.bool("DEBUG", default='runserver' in sys.argv)
ALLOWED_HOSTS = ['api.ibercivis.es', 'geonity.ibercivis.es', 'geonity-backend.ibercivis.es']

# For the API
BASE_URL = env("BASE_URL")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.gis",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "django_countries",
    "allauth.socialaccount", # Para implementar autenticación usando redes sociales
    "allauth.socialaccount.providers.google",

    "django_rq",

    "django_db_logger",

    # My apps
    "project",
    "organizations",
    "field_forms",
    "markers",
    "stats",
    "users.apps.UsersConfig",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "citsci-api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "citsci-api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        #"ENGINE": "django.db.backends.sqlite3",
        #"NAME": BASE_DIR / "db.sqlite3",
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST", default="localhost"),
        "PORT": env("DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = "es"

LANGUAGES = [
    ('es', _('Spanish')),
    ('en', _('English')),
    ('fr', _('French')),
    ('pt', _('Portuguese')),
    ('it', _('Italian')),
    ('de', _('German')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Allow tokens for authentication
REST_FRAMEWORK = {
    # Ojo: aqui habia un segundo 'DEFAULT_PERMISSION_CLASSES': AllowAny que quedaba pisado por el
    # de mas abajo (en un dict literal gana la ultima clave). El comportamiento no cambia; se
    # borra para que nadie lea la equivocada.
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        #'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Vacío a propósito: el throttling se declara vista a vista (de momento solo en los
    # endpoints anónimos del QR), no queremos limitar el resto de la API.
    'DEFAULT_THROTTLE_CLASSES': [],
    'DEFAULT_THROTTLE_RATES': {
        'anon_form': '60/min',
        'anon_submit': '20/hour',
        'anon_submit_id': '10/hour',
        'stats': '30/min',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'citsci-api',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

REST_AUTH = {
    'PASSWORD_RESET_SERIALIZER': 'dj_rest_auth.serializers.PasswordResetSerializer',
    'REGISTER_SERIALIZER': 'users.api.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'users.api.serializers.UserDetailsSerializer',
}

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'users.authentication_backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# As we added django.contrib.sites
SITE_ID = 1

# email to show in the terminal
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# email using amazon ses
EMAIL_BACKEND = 'django_ses.SESBackend'
DEFAULT_FROM_EMAIL = env("FROM_EMAIL")
EMAIL_SUBJECT_PREFIX = '[Geonity]'

ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

GOOGLE_CALLBACK_URL = 'https://geonity-admin.ibercivis.es/auth/google/callback'

SOCIALACCOUNT_STORE_TOKENS = False

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': env('GOOGLE_CLIENT_ID', default=''),
            'secret': env('GOOGLE_CLIENT_SECRET', default=''),
            'key': '',
        }
    }
}
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_ADAPTER = 'users.adapters.CustomSocialAccountAdapter'

# AWS SES
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
# Additionally, if you are not using the default AWS region of us-east-1,
AWS_SES_REGION_NAME = env('AWS_SES_REGION_NAME')
AWS_SES_REGION_ENDPOINT = env('AWS_SES_REGION_ENDPOINT')

CLIENT_API_KEY_MOBILE = env('CLIENT_API_KEY_MOBILE')
CLIENT_API_KEY_WEB = env('CLIENT_API_KEY_WEB')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f"redis://{env('REDIS_HOST', default='localhost')}:{env.int('REDIS_PORT', default=6379)}/1",
        'TIMEOUT': 60 * 60 * 24,  # 24h — se invalida por signal al llegar observaciones
    }
}

RQ_QUEUES = {
    'citisciapi': {
        'HOST': env('REDIS_HOST', default='localhost'),
        'PORT': env.int('REDIS_PORT', default=6379),
        'DB': 0,
        'DEFAULT_TIMEOUT': 360,
    }
}

ADMINS = [('Ibercivis', 'frasanz@ibercivis.es')]

# Destinatarios de los avisos de plataforma: proyecto creado/publicado/despublicado, organizacion
# nueva y resumen periodico. Lista explicita y NO derivada de is_staff a proposito: entre los
# superusuarios hay cuentas de prueba con dominios que no existen, y cada rebote cuenta contra la
# reputacion de envio de SES. Distinto de ADMINS, que Django usa para los tracebacks.
PLATFORM_NOTIFICATION_EMAILS = env.list('PLATFORM_NOTIFICATION_EMAILS', default=[])

# Zona horaria de los envios programados. TIME_ZONE del proyecto sigue siendo UTC y no se toca:
# esto solo decide a que hora local sale el resumen periodico. Con 'Europe/Madrid' el cambio de
# hora se gestiona solo (UTC+2 en verano, UTC+1 en invierno).
PLATFORM_NOTIFICATION_TIMEZONE = env('PLATFORM_NOTIFICATION_TIMEZONE', default='Europe/Madrid')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'db': {
            'level': 'ERROR',
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose',
            'include_html': True,
            'email_backend': 'django.core.mail.backends.smtp.EmailBackend',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['db', 'mail_admins', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['db', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'geonity': {
            'handlers': ['db', 'mail_admins', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}