# Generated by Django 4.1.5 on 2023-05-09 11:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_forms', '0001_initial'),
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('geoposition', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='field_forms.fieldform')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='markers.observation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_forms.question')),
            ],
        ),
        migrations.RemoveField(
            model_name='marker',
            name='field_form',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
