# Generated by Django 4.1.5 on 2023-05-23 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markers', '0002_observation_observationimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
