# Generated by Django 4.1.5 on 2026-01-22 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_project__password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markers', '0003_observation_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectObservationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('field_type', models.CharField(choices=[('bool', 'Boolean'), ('choice', 'Choice'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date')], max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_fields', to='project.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ObservationFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='markers.projectobservationfield')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_field_values', to='markers.observation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_observation_field_values', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectobservationfield',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='uniq_project_observation_field_key'),
        ),
        migrations.AddConstraint(
            model_name='observationfieldvalue',
            constraint=models.UniqueConstraint(fields=('observation', 'field'), name='uniq_observation_admin_field'),
        ),
    ]
