# Generated by Django 4.1.5 on 2026-03-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0004_projectobservationfield_observationfieldvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectobservationfield',
            name='field_type',
            field=models.CharField(choices=[('bool', 'Boolean'), ('choice', 'Choice'), ('mchoice', 'Multichoice'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date')], max_length=16),
        ),
    ]
