# Generated by Django 4.1.5 on 2026-03-08 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markers', '0005_add_multichoice_to_project_observation_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectobservationfield',
            name='include_in_email',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ObservationEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('include_observation_data', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='markers.observation')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_observation_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
