# Generated by Django 4.1.5 on 2026-03-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0006_projectobservationfield_include_in_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectobservationfield',
            old_name='include_in_email',
            new_name='public',
        ),
    ]
