# Generated by Django 5.2.12 on 2026-04-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0008_observation_creator_set_null_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='platform',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('web', 'Web')], max_length=10, null=True),
        ),
    ]
