# Generated by Django 5.2.12 on 2026-04-11 13:22

from django.db import migrations


class Migration(migrations.Migration):
    """
    Convierte geoposition al estándar GeoJSON/PostGIS: Point(lon, lat).
    Hasta ahora se almacenaba al revés: Point(lat, lon).
    """

    dependencies = [
        ('markers', '0009_add_platform_to_observation'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE markers_observation
                SET geoposition = ST_SetSRID(
                    ST_MakePoint(ST_Y(geoposition), ST_X(geoposition)),
                    4326
                );
            """,
            reverse_sql="""
                UPDATE markers_observation
                SET geoposition = ST_SetSRID(
                    ST_MakePoint(ST_Y(geoposition), ST_X(geoposition)),
                    4326
                );
            """,
        ),
    ]
