# Generated by Django 5.2.12 on 2026-04-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0010_swap_geoposition_lat_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationemaillog',
            name='allow_reply',
            field=models.BooleanField(default=False),
        ),
    ]
