# Generated by Django 5.2.12 on 2026-05-26 17:27

import django.db.models.deletion
import markers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_forms', '0012_alter_question_options_alter_question_answer_type'),
        ('markers', '0011_add_allow_reply_to_observationemaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=markers.models.audio_upload_path)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='markers.observation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_forms.question')),
            ],
        ),
    ]
